name: tareas_poli
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3
  provider: ^6.1.2
  flutter_local_notifications: ^14.0.0
  timezone: ^0.9.4
  sqflite: any
  path: any
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.11.0 
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon.png"
